Feature/115
fga-eps-mds/2018.1_Nexte pull request #261
Opened 2018-05-02 03:19 UTC by lorranyh

## Descrição
O usuário pode adicionar um comentário na partida finalizada.

### Qual tipo de mudança o Pull Request introduz?
Adição de um comentário no jogo exibido no feed.

### Qual é o comportanto atual?
Só é possível a visualização dos dados mockados, sem poder inserir um comentário.

### Qual é o novo comportamento?
Agora o usuário pode inserir um comentário novo.

### Quais as issues o Pull Request finaliza?
#115 

### _Uso do avaliador_
- [x] Mensagens de commits seguem a guideline proposta;
- [x] Os testes foram adicionados mantendo ou aumentando a cobertura de testes;
- [x] Documentos necessários foram atualizados ou adicionados;

2018-05-02 03:41 UTC, gabrielalbino commented
@guibaldissera consegue rodar o pipeline manualmente?

2018-05-02 03:50 UTC, guibaldissera commented
Porque rodas o pipeline manualmente @gabrielalbino ?

2018-05-02 04:52 UTC, guibaldissera submitted a review, later dismissed
@lorranyh e @gabrielalbino 
Parabéns! Sem dúvida um dos melhores PRs que analisei até o momento! Todos os critérios de aceitação da issue de acordo, critérios de aceitação do PR aceitos também. Testes realizados, documentação atualizada, código comentado, refatoração de código e testes...

Parabéns!

2018-05-02 11:11 UTC, miguelpimentel commented
@gabrielalbino e @lorranyh  até às 13 hrs eu avalio. Mas, pelo feedback do @guibaldissera deve estar ótimo.

2018-05-02 13:02 UTC, luis-gustavo requested changes
@gabrielalbino @lorranyh Muito bom galera, tudo funcionando de acordo com os critérios de aceitação e legal que vocês atualizaram a documentação.

Mas, eu acho que seria bem se quando o teclado subisse para a pessoa digitar as células da list view subissem também(o teclado tampa o último comentário) e também quando a pessoa clicasse em qualquer lugar da tela, seria legal que o teclado sumisse. Isso não está nos critérios de aceitação, então não é obrigatório que coloquem, mas acho que seria legal.

E galera, como combinamos essa sprint a cobertura mínima é 50% e a branch de vocês está em 48%, subam esses 2% para esse PR ser aceito.
![](https://i.imgur.com/V9q8zK3.png)

2018-05-02 16:59 UTC, gabrielalbino commented
Retirei o Baldissera de reviewer sem querer querendo :p

Galera fiz as mudanças necessárias
1 - Adicionei mais alguns testes, se não for o suficiente avisa ae (não ser ver a cobertura)
2 - Adicionei opção do teclado fechar porem ela n funciona se o usuário clicar em um comentário, só na foto ou na data ou no botão de enviar (não achei uma solução pra isso pois parece algo bem especifico da scrollView)
3 - Adicionei opção de rolagem para o fim da lista ao teclado abrir ou adicionar novo comentário, porem a lista não está sendo redimensionada e não sei como soluciona isso (segui alguns tutoriais e até alterei o manifest, mas sem sucesso (As constraints estão ok, então deve ser outro problema))

2018-05-02 17:03 UTC, luis-gustavo requested changes
@gabrielalbino @lorranyh Legal ver que fizeram as alterações, a gente dá uma olhada pra ver como resolver esse problema.

Só que a cobertura ainda está em 48%, precisa, necessariamente, subir para 50% para ser aceito.

Se tiver dúvidas de como visualizar a cobertura olha os comentários desse [pull request](https://github.com/fga-gpp-mds/2018.1_Nexte/pull/240) lá eu explico como faz para ver.

2018-05-02 22:54 UTC, gabrielalbino commented
@luis-gustavo uma duvida
analisando a analise (lul) vi que não testei todas as possibilidades desse metodo:
![image](https://user-images.githubusercontent.com/30835149/39553125-7ef68c6a-4e42-11e8-9602-4616e2c520a7.png)
```
override fun presentNewComment(response: CommentsModel.PublishCommentRequest.Response) {

        val newComment = response.newComment

        val formatted = CommentsModel.CommentFormatted(
                newComment.comment,
                newComment.date.toString(),
                newComment.author.name,
                newComment.author.photo
        )

        val viewModel = CommentsModel.PublishCommentRequest.ViewModel(formatted)

        viewController?.displayPublishedComment(viewModel)
    }
```

seria por causa da verificação do not null?
`viewController?.displayPublishedComment(viewModel)`

2018-05-02 23:17 UTC, luis-gustavo commented
@gabrielalbino Tem que ver direitinho o porquê disso, a cobertura especificamente não é dada pelo número de coisas que são testadas, mas sim pelo número de linhas que são "cobertas" por testes.

2018-05-03 01:47 UTC, luis-gustavo approved these changes
Show, agora está tudo certo @gabrielalbino

2018-05-03 02:21 UTC, miguelpimentel commented on docs/MDS/DocArquitetura.md
> +![Diagrama de classes da comments](https://i.imgur.com/wXlln8C.jpg)
Boa!

2018-05-03 02:22 UTC, miguelpimentel commented on project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsPresenter.kt
> +        val formatted = CommentsModel.CommentFormatted(
show!

2018-05-03 02:23 UTC, miguelpimentel commented on project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsView.kt
> +    /**
Ótimo uso de privates

2018-05-03 02:24 UTC, miguelpimentel commented on project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsModelTest.kt
> +    fun successFirstResponseSet(){
Aleluia testes!

2018-05-03 02:25 UTC, miguelpimentel approved these changes
@gabrielalbino  e @lorranyh, parabéns! Muito bom, e antes do final da nossa sprint, muito satisfeito com o trabalho de vocês

2018-05-03 02:25 UTC, merged