Feature/117
fga-eps-mds/2018.1_Nexte pull request #281
Opened 2018-05-09 04:27 UTC by larissa-sales

## Descrição
Atualização da cena de ranking, alterando a visibilidade da célula do jogador logado

### Qual tipo de mudança o Pull Request introduz?
Adiciona uma funcionalidade que faz com que a célula do jogador logado na cena de ranking fique fixa na tela ao realizar rolagem.

### Qual é o comportamento atual?
O usuário logado só consegue ver sua posição no ranking ao rolar a tela.

### Qual é o novo comportamento?
O usuário logado consegue ver sua posição no ranking sem rolar a tela

### Quais as issues o Pull Request finaliza?
#117 

### _Uso do avaliador_
- [ ] Mensagens de commits seguem a guideline proposta;
- [ ] Os testes foram adicionados mantendo ou aumentando a cobertura de testes;
- [ ] Documentos necessários foram atualizados ou adicionados;

2018-05-09 11:36 UTC, miguelpimentel commented
@larissa-sales, o pipeline está quebrando na análise estática e testes.

2018-05-10 07:41 UTC, guibaldissera submitted a review, later dismissed
Muito Bom! Parabéns aos envolvidos! Ao meu ver já está suficiente e aceitável! 
Se quiserem fazer algumas melhorias, fiquem a vontade:
* Quando clica na "célula" fixa, a célula que está abaixo expande, por certo não deveria;
* Seria legal já fixar a célula quando ela encosta nas margens da tela, e não quando ela já saiu;
* Seria interessante também, ao clicar na "célula" fixa, dar um scroll na RecyclerView, posicionando-a no usuário.

2018-05-10 12:03 UTC, luis-gustavo requested changes
@larissa-sales @gabrielalbino Muito bom trabalho galera!

Mas só lembrando que a cobertura de testes mínima para essa sprint é 55%. Não tem como ser aceito sem chegar nesse valor.

2018-05-10 12:20 UTC, miguelpimentel commented on project/app/src/main/java/com/nexte/nexte/RankingScene/RankingView.kt
> +        if(layoutManager.findFirstCompletelyVisibleItemPosition() <= playerRanking - 1
Bom, sempre ótimo quebrar linhas!

2018-05-10 12:22 UTC, miguelpimentel commented on project/app/src/main/java/com/nexte/nexte/RankingScene/RankingView.kt
> +    private class OnScrollRankingRecyclerView(val playerRanking: Int, val context: Context) : RecyclerView.OnScrollListener() {
Não seria legal quebrar essas, por exemplo

````
private class OnScrollRankingRecyclerView(val playerRanking: Int,
                                          val context: Context) : RecyclerView.OnScrollListener() {
````

2018-05-10 12:22 UTC, miguelpimentel commented on project/app/src/main/java/com/nexte/nexte/RankingScene/RankingView.kt
> +        private var expandedId = -1
muito bom! privates sz

2018-05-10 12:25 UTC, miguelpimentel reviewed
Muito bom! Parabéns aos responsáveis. Deixei algumas considerações que ficam a desejo dos participantes mudar ou não, ainda mais com 32843843 de coisas para fazer.  Só a questão dos testes. Mas, muito bom. Os PR's do time e de todos estão muito melhores. Bom Trabalho.

2018-05-10 13:38 UTC, Geovannioj reviewed
Show! muito bom, só falta aumentar a cobertura que é só aprovar!

2018-05-11 00:49 UTC, gabrielalbino commented on project/app/src/main/java/com/nexte/nexte/RankingScene/RankingView.kt
> +    private class OnScrollRankingRecyclerView(val playerRanking: Int, val context: Context) : RecyclerView.OnScrollListener() {
Tava quebrando o detekt

2018-05-11 12:04 UTC, luis-gustavo commented
@larissa-sales @gabrielalbino Só falta 1% galera

2018-05-11 12:33 UTC, luis-gustavo approved these changes

2018-05-11 12:49 UTC, miguelpimentel approved these changes
Agora sim, parabéns time.

2018-05-11 12:49 UTC, merged