Feature/249
fga-eps-mds/2018.1_Nexte pull request #291
Opened 2018-05-11 13:30 UTC by luis-gustavo

## Descrição
Refatoração da likelistscene, adicionando a manager e mudando alterando a comunicação entre interactor e worker para se comunicarem via interfaces.

### Qual tipo de mudança o Pull Request introduz?
Refatoração da likelistscene

### Qual é o comportanto atual?
Essas classes se comunicam via completion e a manager não está inserida nessa cena

### Qual é o novo comportamento?
Essas classes se comunicam via interfaces e a manager está nessa cena

### Quais as issues o Pull Request finaliza?
#249 

### _Uso do avaliador_
- [ ] Mensagens de commits seguem a guideline proposta;
- [ ] Os testes foram adicionados mantendo ou aumentando a cobertura de testes;
- [ ] Documentos necessários foram atualizados ou adicionados;

2018-05-11 13:33 UTC, luis-gustavo commented
A cobertura está caindo em em 53% pois eu tive que comentar alguns testes que fiz da worker. Estão quebrando alguns testes que utilizam o realm. É possível mockar o realm mas está bem fora do escopo dessa issue. Creio que o ideal seria realizar os testes de mockar o realm em uma issue separada ou então junto com a issue de testar view, visto que o processo é parecido.

Aguardando feedback.

2018-05-11 14:12 UTC, miguelpimentel commented on project/app/src/main/java/com/nexte/nexte/LikeListScene/LikeListInteractor.kt
> +interface UpdateResponseLogic {
Coloca um comentário aqui na iterface, só para seguir a folha de estilo.

2018-05-11 14:14 UTC, miguelpimentel commented on project/app/src/test/java/com/nexte/nexte/LikeListScene/LikeListWorkerTest.kt
> +class MockUpdateResponseLogic: UpdateResponseLogic {
Boa!

2018-05-11 14:15 UTC, miguelpimentel commented on project/app/src/test/java/com/nexte/nexte/LikeListScene/LikeListWorkerTest.kt
>  class LikeListWorkerTest {
Boa, testando as novas interfaces

2018-05-11 17:50 UTC, miguelpimentel reviewed
Tá muito bom, que bom que conseguiu sacar a arquitetura. Conversei com @guibaldissera  e decidimos mudar o nome default do protocolo de volta, para workerUpdateLogic. Boa @luis-gustavo

2018-05-11 17:54 UTC, guibaldissera requested changes
Legal Luis, ficou bom, falta só umas adequações de nomeclatura para melhor entendimento.

2018-05-11 17:54 UTC, guibaldissera commented on project/app/src/main/java/com/nexte/nexte/LikeListScene/LikeListInteractor.kt
> +interface UpdateResponseLogic {
Muda o nome dessa interface para *WorkerUpdateLogic*
Essa interface deve ser definida na Worker, e não aqui na Interactor

2018-05-11 17:54 UTC, guibaldissera commented on project/app/src/main/java/com/nexte/nexte/LikeListScene/LikeListInteractor.kt
> +    fun getUsers(response: LikeListModel.Response)
Esse método seria melhor que fosse updateUsers ou algo nesse sentido.

2018-05-11 17:54 UTC, guibaldissera commented on project/app/src/main/java/com/nexte/nexte/LikeListScene/LikeListWorker.kt
> +    var responseLogic: UpdateResponseLogic? = null
Talvez seria melhor ser updateLogic

2018-05-11 17:54 UTC, guibaldissera commented on project/app/src/main/java/com/nexte/nexte/LikeListScene/LikeListWorker.kt
> +        val response = LikeListModel.Response(this.generateLikeList(request = request))
Acho que o método generateLikeList deveria ser diferente, acho que a Manager deveria ser usada aqui mesmo, e em vez de generateLikeList, deveria ser algo para conversão do User para LikeListModel.Players, apenas.

2018-05-11 21:11 UTC, Geovannioj submitted a review, later dismissed

2018-05-11 21:56 UTC, luis-gustavo commented
@guibaldissera Corrigido!

2018-05-11 21:56 UTC, miguelpimentel submitted a review, later dismissed
Agora sim, boa @luis-gustavo.

2018-05-12 04:11 UTC, guibaldissera approved these changes

2018-05-12 11:51 UTC, miguelpimentel approved these changes
Boa, @luis-gustavo

2018-05-12 11:52 UTC, merged