Feature/315
fga-eps-mds/2018.1_Nexte pull request #318
Opened 2018-05-22 15:55 UTC by luis-gustavo

## Descrição
Esse pr adiciona os dados reais no ranking, já fazendo a integração com o servidor.

### Qual tipo de mudança o Pull Request introduz?
Dados reais no ranking junto com a integração do servidor

### Qual é o comportanto atual?
Os dados do ranking são gerados na propria worker e não há integração com o servidor

### Qual é o novo comportamento?
Os dados do ranking vem da UserManager(para os dados mockados) e do servidor(para os dados reais)
### Quais as issues o Pull Request finaliza?
#315 

### _Uso do avaliador_
- [ ] Mensagens de commits seguem a guideline proposta;
- [ ] Os testes foram adicionados mantendo ou aumentando a cobertura de testes;
- [ ] Documentos necessários foram atualizados ou adicionados;

2018-05-23 01:02 UTC, miguelpimentel commented on project/app/src/main/java/com/nexte/nexte/RankingScene/RankingView.kt
> +    fun setupRankingScene(userMananger: UserManager = UserManager()){
Agora sim!

2018-05-23 01:03 UTC, miguelpimentel commented on project/app/src/main/java/com/nexte/nexte/RankingScene/RankingWorker.kt
> +        val url = "http://10.0.2.2:3000/users"
Isso aqui é demais, vamos ter que utilizar em outros lugares da aplicação.

2018-05-23 01:03 UTC, miguelpimentel commented on project/app/src/main/java/com/nexte/nexte/RankingScene/RankingWorker.kt
> +    private fun createUser(jsonUser: JSONObject): User{
Agora sim!

2018-05-23 01:04 UTC, miguelpimentel commented on project/app/src/main/java/com/nexte/nexte/RankingScene/RankingWorker.kt
> +        if(today.year == latestGameDate.year){
Isso não está muito bonito, mas por agora está ótimo. Alta complexidade Hehe

2018-05-23 01:04 UTC, miguelpimentel commented on project/app/src/test/java/com/nexte/nexte/RankingScene/RankingWorkerTest.kt
> +        RxJavaPlugins.setNewThreadSchedulerHandler { Schedulers.trampoline() }
Esta forma de adicionar a nova thread foi muito bom,

2018-05-23 01:05 UTC, miguelpimentel submitted a review, later dismissed
Muito bom, @luis-gustavo. Tudo certo, muito bom fechar histórias ainda na terça. Gostei muito de algumas coisas que utilizou.

2018-05-23 01:14 UTC, luis-gustavo commented on project/app/src/test/java/com/nexte/nexte/RankingScene/RankingWorkerTest.kt
> +        RxJavaPlugins.setNewThreadSchedulerHandler { Schedulers.trampoline() }
Na verdade isso ai não está fazendo nada kkk, é um código perdido que esqueci de apagar

2018-05-23 03:45 UTC, guibaldissera requested changes
@luis-gustavo, ficou muito bom! Parabéns! Muito rápido também, inclusive hahahaha
Aquelas perguntas que você fez no Slack, sobre ChallengeReceived e ChallengeSended, e sobre a latestChallenges, challengeReceived e ChallengeSended você não precisa se preocupar... Já a LatestChallenges, você precisaria fazer um método na ChallengeManager para buscar os últimos 5 jogos do usuário, ordenando pela data... Independente se o usuário é challenger ou challenged.

2018-05-23 03:45 UTC, guibaldissera commented on project/app/src/main/java/com/nexte/nexte/RankingScene/RankingWorker.kt
> +    private fun convertUsersToRankingModelPlayers(users: List<User>): Array<RankingModel.Player> {
Luis, acho que não precisaríamos fazer essa conversão aqui, estamos fazendo 3 conversões... JSON -> User, User -> Player, Player -> FormattedPlayerInfo...
Talvez, se não achares ruim, faz a alteração do Response pra ele ir um Array de Users, e lá na presenter a conversão é direta de User para FormattedPlayerInfo;
Isso tiraria daqui alguns métodos e jogaria eles lá pra Presenter, como o *calculatePlayerEfficiency* e * calculatePlayerLastGame*... Até porque, quem faz essas coisas é a própria presenter, e não a Worker

2018-05-23 03:47 UTC, guibaldissera commented
Outra coisa que esqueci, você fez um método createUser na worker para criar um usuário a partir de um JSON certo?
O mais interessante seria fazer esse método lá na Entity de User mesmo... Criar um contrutor secundário que faz isso... recebe o JSON e cria o objeto a partir desse JSON

2018-05-23 16:57 UTC, luis-gustavo commented
@guibaldissera Arrumado! Aguardando novos feedbacks

2018-05-23 17:18 UTC, guibaldissera requested changes
Tá quase! haha gogogo Luis, hoje acaba

2018-05-23 17:18 UTC, guibaldissera commented on project/app/src/main/java/com/nexte/nexte/Entities/Challenge/ChallengeAdapterRealm.kt
> +        val allChallengeRealm = realm.where<ChallengeRealm>().findAll()
Não man, tu pode fazer o filtro e o sort direto aqui no realm... Não precisa trazer tudo do banco para depois criar métodos para fazer as coisas pra você...
Teria que ser algo tipo: 
relm.where<ChallengeRealm>().equalTo("", "").or().equalTo("", "").sort("").findAll()
Daí após isso você precisa fazer algo pra pegar os 5 primeiros resultados.

2018-05-23 17:18 UTC, guibaldissera commented on project/app/src/main/java/com/nexte/nexte/Entities/User/User.kt
> +        fun createUserFromJsonObject(jsonUser: JSONObject, challengeAdapter: ChallengeAdapter = ChallengeAdapterRealm()): User {
Aqui seria um construtor mesmo, não uma função...
E não pode-se fazer referências a Challenge aqui. Os atributos com esse tipo de informação, devem ser iniciados com null.

2018-05-23 17:18 UTC, guibaldissera commented on project/app/src/main/java/com/nexte/nexte/RankingScene/RankingView.kt
> +    fun setupRankingScene(userMananger: UserManager = UserManager()){
Por certo você deveria criar o UserManager ali como foi criado a presenter e a interactor, no meio do código, e não aqui na declaração da função.

2018-05-23 23:31 UTC, luis-gustavo commented on project/app/src/main/java/com/nexte/nexte/Entities/User/User.kt
> +        fun createUserFromJsonObject(jsonUser: JSONObject, challengeAdapter: ChallengeAdapter = ChallengeAdapterRealm()): User {
Sim, eu tentei fazer isso inicialemente mas não consegui. Para criar um construtor secundário eu preciso chamar o construtor primeiro de imediato(o que não tem como fazer pq não tenho os dados ainda, estão dentro do json). Se eu iniciá-los com um valor default eu não consigo reatribuir pq são constantes(*val*).

2018-05-24 13:29 UTC, guibaldissera approved these changes
Show man! Agora ficou show

2018-05-24 13:30 UTC, miguelpimentel approved these changes

2018-05-24 13:30 UTC, merged