Feature/140
fga-eps-mds/2018.1_Nexte pull request #322
Opened 2018-05-25 01:21 UTC by larissa-sales

## Descrição
Este pull request atualiza o feed de atividades com um novo design.

### Qual tipo de mudança o Pull Request introduz?
Modifica o layout e a apresentação dos dados na tela.

### Qual é o comportamento atual?
O layout não está seguindo o padrão do aplicativo.

### Qual é o novo comportamento?
O layout agora segue o padrão do aplicativo.

### Quais as issues o Pull Request finaliza?
#140 

### _Uso do avaliador_
- [ ] Mensagens de commits seguem a guideline proposta;
- [ ] Os testes foram adicionados mantendo ou aumentando a cobertura de testes;
- [ ] Documentos necessários foram atualizados ou adicionados;

2018-05-25 18:41 UTC, guibaldissera requested changes
* Faltou fazer o botão de "Like", ficar normal caso dê dislike.
* A pasta site/ foi adicionada ao projeto. Por favor retirar.

2018-05-25 22:35 UTC, luis-gustavo submitted a review, later dismissed
Show!

2018-05-26 02:03 UTC, larissa-sales commented
@guibaldissera tudo ok agora, eu espero hahaha

2018-05-26 12:39 UTC, miguelpimentel approved these changes
Agora sim, desculpa a demora. Vimos, que o @guibaldissera tinha solicitado modificações e então esperamos essas alterações para avaliar de novo. Estou com probleminhas no simulador e só vou ter tempo para arrumar amanhã, desculpa o atraso. Semana que vem este problema vai ter desaparecido

2018-05-26 19:01 UTC, guibaldissera approved these changes
Boa pessoal!

2018-05-26 19:03 UTC, merged