Feature/121 2
fga-eps-mds/2018.1_Nexte pull request #328
Opened 2018-05-26 14:35 UTC by gabrielalbino

## Descrição
* Ranking  agora exibe os jogadores e ordem de posição do Ranking
* Agora ao clicar no botão de "perfil" de algum usuário no ranking
* Se o botão de perfil clicado for o do usuário logado, o botão de exibir perfil é exibido

### Qual tipo de mudança o Pull Request introduz?
Adiciona a opção do usuário acessar o perfil de outras pessoas

### Qual é o comportanto atual?
O usuário pode apenas acessar seu próprio perfil

### Qual é o novo comportamento?
O usuário consegue acessar o perfil de qualquer jogador presente no ranking

### Quais as issues o Pull Request finaliza?
#121 

### _Uso do avaliador_
- [ ] Mensagens de commits seguem a guideline proposta;
- [ ] Os testes foram adicionados mantendo ou aumentando a cobertura de testes;
- [ ] Documentos necessários foram atualizados ou adicionados;

2018-05-26 22:07 UTC, gabrielalbino commented
@guibaldissera corrigi as 2 navbar

2018-05-26 23:12 UTC, luis-gustavo submitted a review, later dismissed
@gabrielalbino @helenagoulart Show, só corrigir o conflito agora

2018-05-27 01:34 UTC, guibaldissera requested changes
Muito bom manin, falta só ajustar a Worker do profile

2018-05-27 01:34 UTC, guibaldissera commented on project/app/src/main/java/com/nexte/nexte/LoginScene/LoginModel.kt
> +           const val accountKit_code = 13
Isso aí senhor, ajustando algo que não é de vocês! Muito bom

2018-05-27 01:34 UTC, guibaldissera commented on project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileWorker.kt
> +        val userList = UserMocker.generateUsers()
Aqui... Aqui deveria ser usada a UserManager... tem que passar o ID do usuário pra Manager, chamando o método Get dela, e ela retornará pra você o usuário que tu quer.

2018-05-27 19:56 UTC, guibaldissera approved these changes

2018-05-27 20:08 UTC, luis-gustavo approved these changes

2018-05-27 20:08 UTC, merged