Feature/336
fga-eps-mds/2018.1_Nexte pull request #341
Opened 2018-05-29 13:29 UTC by miguelpimentel

## Descrição
Adiciona o planejamento para a Sprint 12

### Qual tipo de mudança o Pull Request introduz?
Planejamento da Sprint 12.

### Qual é o comportanto atual?
Não há documentação referente a esta nova sprint.

### Qual é o novo comportamento?
Planejamento desta nova sprint.

### Quais as issues o Pull Request finaliza?
#336 

### _Uso do avaliador_
- [ ] Mensagens de commits seguem a guideline proposta;
- [ ] Os testes foram adicionados mantendo ou aumentando a cobertura de testes;
- [ ] Documentos necessários foram atualizados ou adicionados;

2018-05-29 16:49 UTC, luis-gustavo requested changes
@miguelpimentel Falta a parte de pareamentos e também falta adicionar esse arquivo no mkdocs.yml

2018-05-29 16:49 UTC, luis-gustavo requested changes
@miguelpimentel Falta a parte de pareamentos e também falta adicionar esse arquivo no mkdocs.yml

2018-05-31 00:27 UTC, Geovannioj commented on docs/Sprints/Sprint12/Sprint12-Planejamento.md
> +**Número da Sprint:** 11
O número da Sprint é o 12, só atualizar isso aí mesmo.

2018-05-31 02:23 UTC, guibaldissera submitted a review, later dismissed

2018-05-31 07:00 UTC, Geovannioj submitted a review, later dismissed

2018-05-31 18:54 UTC, luis-gustavo approved these changes

2018-05-31 18:55 UTC, luis-gustavo commented
@miguelpimentel Tudo certo agora

2018-05-31 18:59 UTC, Geovannioj approved these changes

2018-05-31 18:59 UTC, merged