Feature/128
fga-eps-mds/2018.1_Nexte pull request #343
Opened 2018-05-30 02:31 UTC by helenagoulart

## Descrição
Design aplicado na LikeList.

### Qual tipo de mudança o Pull Request introduz?
A LikeList agora é um fragment, e ela tem o design aplicado.

### Qual é o comportanto atual?
O design está de acordo com a versão IOS.

### Quais as issues o Pull Request finaliza?
128

### _Uso do avaliador_
- [ ] Mensagens de commits seguem a guideline proposta;
- [ ] Os testes foram adicionados mantendo ou aumentando a cobertura de testes;
- [ ] Documentos necessários foram atualizados ou adicionados;

2018-05-30 23:40 UTC, miguelpimentel commented
@helenagoulart  @lorranyh  o pipeline está quebrado.

2018-05-31 02:01 UTC, lorranyh commented
@miguelpimentel agora está passando

2018-05-31 02:24 UTC, Geovannioj submitted a review, later dismissed
Muito bom @helenagoulart  e @lorranyh

2018-05-31 02:36 UTC, guibaldissera requested changes
Ajustar algumas coisinhas no código, e o design não está totalmente fiel, segue prints kkkk

* A imagem interna deve ficar redonda também, e ela deve ocupar toda a parte interna do círculo.
* O nome da pessoa não está centralizado na imagem.

<img width="267" alt="captura de tela 2018-05-30 as 23 33 16" src="https://user-images.githubusercontent.com/17801101/40758136-35098b44-6462-11e8-861b-b8addc2db2f0.png">
<img width="188" alt="captura de tela 2018-05-30 as 23 35 09" src="https://user-images.githubusercontent.com/17801101/40758137-35290cee-6462-11e8-86ee-86f8880fff60.png">

2018-05-31 02:36 UTC, guibaldissera commented on project/app/src/main/java/com/nexte/nexte/FeedScene/FeedFragment.kt
> +      //  val intent = Intent(activity, LikeListFragment::class.java)
Código comentado pode ser removido.

2018-05-31 02:36 UTC, guibaldissera commented on project/app/src/main/java/com/nexte/nexte/MainActivity.kt
> +            R.id.login -> {
Porque isso? Essa Issue não mexe com isso acho kkkk

2018-05-31 19:38 UTC, lorranyh commented on project/app/src/main/java/com/nexte/nexte/MainActivity.kt
> +            R.id.login -> {
era só um teste, mas tentei isso na branch errada kkkk

2018-05-31 20:02 UTC, guibaldissera approved these changes

2018-05-31 20:32 UTC, Geovannioj approved these changes
Nice!

2018-05-31 20:32 UTC, merged