Feature/323
fga-eps-mds/2018.1_Nexte pull request #344
Opened 2018-05-30 04:28 UTC by aleronupe

## Descrição
O Pull Request separa a classe TabFragment da ChallengeFragment, criando assim um fragment específicopara o gerenciamento de Tabs e separando uma cena similar à atual _Challenge_ como um _fragment_ que será inicializado dentro do fragment de Tabs.

### Qual tipo de mudança o Pull Request introduz?

* Criação de uma nova cena "PlayersListScene";
* Criação de um novo fragment "Tabs";
* Adição da cena de desafio como fragment pela junção das Cenas criadas nessa issue;
* Criação de uma cena para desafio recebido similar à de desafio enviado;

### Qual é o comportanto atual?

* Existe uma cena como Activity, mesclando o gerenciamento de Tabs e a Escolha de Players para sere desafiados;
* Não existe cena específica para desafio enviado;

### Qual é o novo comportamento?

* A Cena de desafios funciona como fragment, com um fragment específico para gerenciamento de tabs que, por sua vez, instancia 2 fragments diferentes para representar os estágios do desafio;

### Quais as issues o Pull Request finaliza?
#323 

### _Uso do avaliador_
- [ ] Mensagens de commits seguem a guideline proposta;
- [ ] Os testes foram adicionados mantendo ou aumentando a cobertura de testes;
- [ ] Documentos necessários foram atualizados ou adicionados;

2018-05-30 23:54 UTC, miguelpimentel commented on project/app/src/main/java/com/nexte/nexte/Entities/Comment/CommentMocker.kt
> -        val date = Date(year, monthOfYear, dayOfYear)
goxtei

2018-05-30 23:54 UTC, miguelpimentel commented on project/app/src/main/java/com/nexte/nexte/Entities/Comment/CommentAdapterRealm.kt
> +    override fun updateOrInsert(challenge: Comment): Comment? {
por quê challenge? Não entendi.

2018-05-31 00:01 UTC, miguelpimentel commented on project/app/src/main/java/com/nexte/nexte/Entities/Like/LikeAdapterRealm.kt
> -        for(likeRealm in likeRealm) {
bom

2018-05-31 00:07 UTC, miguelpimentel commented on project/app/src/main/java/com/nexte/nexte/Entities/Like/LikeMocker.kt
> +        for (counter in 0 until usersIds.size){
muito bom

2018-05-31 00:08 UTC, miguelpimentel commented on project/app/src/main/java/com/nexte/nexte/Entities/User/User.kt
> +                    Status.AVAILABLE
Muito Bom

2018-05-31 00:10 UTC, miguelpimentel submitted a review, later dismissed
Eu avaliei por alto, porque pqp que refatoração do caralho! Muito grande! Gostei muito do estilo de código e da refatoração. Parabéns @gabrielalbino  e @aleronupe

2018-05-31 01:34 UTC, guibaldissera commented on project/app/src/main/java/com/nexte/nexte/Entities/Comment/CommentAdapterRealm.kt
> +    override fun updateOrInsert(challenge: Comment): Comment? {
Isso realmente não faz muito sentido kkkkk

2018-05-31 02:19 UTC, guibaldissera requested changes
Show senhores! Só ajustar realmente aquele nome errado lá

2018-05-31 02:19 UTC, guibaldissera commented on project/app/src/main/java/com/nexte/nexte/Entities/Comment/CommentAdapterRealm.kt
> +    override fun updateOrInsert(challenge: Comment): Comment? {
Precisa voltar para comment!

2018-05-31 18:32 UTC, Geovannioj approved these changes

2018-05-31 18:36 UTC, guibaldissera approved these changes

2018-05-31 18:37 UTC, merged