Feature/326
fga-eps-mds/2018.1_Nexte pull request #347
Opened 2018-06-02 03:04 UTC by mbslet

## Descrição
Esse Pull Request traz o design da tela de editar perfil
### Qual tipo de mudança o Pull Request introduz?
O design da Edit Profile de acordo com o estabelecido
### Qual é o comportanto atual?
Edit Profile possui um visual simples

### Qual é o novo comportamento?
Um novo deign para a cena da Edit Profile
### Quais as issues o Pull Request finaliza?
#326 
### _Uso do avaliador_
- [ ] Mensagens de commits seguem a guideline proposta;
- [ ] Os testes foram adicionados mantendo ou aumentando a cobertura de testes;
- [ ] Documentos necessários foram atualizados ou adicionados;

2018-06-02 19:36 UTC, guibaldissera requested changes
Lamento muito tudo isso, mas não aceitei o design =(

* Os Inputs do usuário são as próprias Descrições... Vocês usaram dois campos em cada linha... é apenas um, onde o placeholder é o que está descrito no Design;

* Existe uma margem entre a linha e a foto, na foto de perfil ali, no design não tem isso.

* O campo de nome, como é um só, pode-se retirar a linha central separando o nome completo para nada.. kkkk

<img width="366" alt="captura de tela 2018-06-02 as 16 30 11" src="https://user-images.githubusercontent.com/17801101/40880156-45635246-6682-11e8-9bf9-82e7d5b0e738.png">
<img width="401" alt="captura de tela 2018-06-02 as 16 29 28" src="https://user-images.githubusercontent.com/17801101/40880158-4582f2a4-6682-11e8-87dc-59b7c1b266ea.png">

2018-06-02 19:48 UTC, mbslet commented
Ahh entendi, achei que no exemplo do zeplin tinha uma descrição a parte, vou ajustar

2018-06-03 06:23 UTC, guibaldissera commented
@mbslet Não está aparecendo as informações do tenista na tela de show profile, não sei se é por isso, mas o botão de editar também não aparece... não estou conseguindo visualizar a tela... =(
Viu, acho que foi o @luis-gustavo que mexeu na get user do Profile... e pelo que vi, o botão aparece na tela quando o usuário logado é o mesmo do usuário que veio da Worker... Por algum motivo maneiro, a Worker não retorna o usuário mockado... Se tu puder ver com o Luís, provavelmente eles terão que dar uma olhada novamente na issue deles.

2018-06-03 06:24 UTC, guibaldissera commented
@luis-gustavo 
<img width="402" alt="captura de tela 2018-06-03 as 03 24 03" src="https://user-images.githubusercontent.com/17801101/40883881-a25586f8-66dd-11e8-999a-412968030d6c.png">

2018-06-03 06:26 UTC, guibaldissera commented
Viu, mas mesmo assim, validei aqui a tela que você ajustou, fiz o botão de editar ficar sempre disponível... A tela melhorou, mas por causa do auto-layout não bom, ela ficou zoada ainda kkkkkkk
Mas acho que está aceitável =)

2018-06-03 06:28 UTC, guibaldissera commented
@luis-gustavo pelo que entendi, isso acontece quando o servidor não está sendo executado na máquina. O servidor não está acessível, daí não encontra nada na worker, consequentemente o usuário não tem nome, daí não aparece o botão de editar perfil...

2018-06-03 14:39 UTC, luis-gustavo commented
@mbslet @guibaldissera Desculpa a demora, to vendo isso ai agora

2018-06-03 20:45 UTC, luis-gustavo commented
@guibaldissera @mbslet A integração com o servidor está funcionando normalmente agora

2018-06-03 22:31 UTC, miguelpimentel commented
tudo bem @luis-gustavo.

2018-06-03 22:31 UTC, miguelpimentel commented
Vou resolver esse pipeline agora com a @mbslet.

2018-06-03 22:55 UTC, luis-gustavo approved these changes
Tudo certo agora galera

2018-06-04 01:09 UTC, mbslet commented
e ai

2018-06-04 03:51 UTC, guibaldissera approved these changes

2018-06-04 03:51 UTC, merged