Feature/324
fga-eps-mds/2018.1_Nexte pull request #371
Opened 2018-06-06 19:48 UTC by helenagoulart

## Descrição
A cena de login foi finalizada.

### Qual tipo de mudança o Pull Request introduz?
Há um novo botão de navegar pelo Nexte sem precisar fazer o login, e agora a cena tem o design aplicado.

### Quais as issues o Pull Request finaliza?
 #324

### _Uso do avaliador_
- [ ] Mensagens de commits seguem a guideline proposta;
- [ ] Os testes foram adicionados mantendo ou aumentando a cobertura de testes;
- [ ] Documentos necessários foram atualizados ou adicionados;

2018-06-07 01:12 UTC, guibaldissera requested changes
Conforme problemas conversado na reunião, esse PR será recusado.

2018-06-08 02:42 UTC, lorranyh commented
@guibaldissera agora as imagens estão com o plano de fundo correto

2018-06-08 03:31 UTC, guibaldissera approved these changes
ok

2018-06-08 13:24 UTC, luis-gustavo approved these changes
Muito bom galera!

2018-06-08 13:24 UTC, merged