Feature/424
fga-eps-mds/2018.1_Nexte pull request #426
Opened 2018-06-15 23:29 UTC by miguelpimentel

## Descrição
Adiciona os Benchmarks do iOS

### Qual tipo de mudança o Pull Request introduz?
Adiciona os Benchmarks do iOS

### Qual é o comportanto atual?
Não há benchamarks do projeto

### Qual é o novo comportamento?
Novos dados sobre performance

### Quais as issues o Pull Request finaliza?
#424 

### _Uso do avaliador_
- [ ] Mensagens de commits seguem a guideline proposta;
- [ ] Os testes foram adicionados mantendo ou aumentando a cobertura de testes;
- [ ] Documentos necessários foram atualizados ou adicionados;

2018-06-16 00:54 UTC, gabrielalbino submitted a review, later dismissed
Achei estranho a quantidade de arquivos, mas não especifica em nenhum lugar como testar se eles são necessários ou as funcionalidades dele vou aprovar e deixar o @guibaldissera aprovar ou não de acordo com o que ele achar adequado

2018-06-16 01:22 UTC, Geovannioj submitted a review, later dismissed
Realmente tem muitos arquivos e poucos que dá pra avaliar o conteúdo, esses pra mim estão tranquilos. Tá aprovado @miguelpimentel.

2018-06-16 05:07 UTC, guibaldissera requested changes
Cara, como o pessoal ali comentou... Tem 250 arquivos modificados modificados, alguns do tipo "bin", alguns "xml", outros "plist", outros que nem sei o que é, do tipo "cred"... vamos analisar melhor isso aí antes de adicionar essa pancada toda de coisas...
Pelo que vi aqui, tem como exportar um arquivo CSV com os dados no "instrument" Miguel.

2018-06-16 05:07 UTC, guibaldissera commented on docs/Benchmarks/Benchmark.md
> +A medição da aplicação iOS foi realizada por meio do *instruments*, e os arquivos com os *benchmarks* encontram-se disponíveis neste resposiório. Além disso, foram realizados *benchmarks* para casa u
Tem uma palavra escrita errado "resposiório"

2018-06-16 05:08 UTC, guibaldissera commented
@miguelpimentel E você nunca, na vida, lembra de conectar a issue ao PR...

2018-06-16 23:21 UTC, gabrielalbino commented
Falta o pipeline ^^

2018-06-20 01:57 UTC, guibaldissera approved these changes

2018-06-20 02:16 UTC, gabrielalbino approved these changes
belo documento ^_^

2018-06-20 06:17 UTC, merged