Feature/374
fga-eps-mds/2018.1_Nexte pull request #427
Opened 2018-06-18 03:59 UTC by gabrielalbino

## Descrição
Esse pr tem o intuito de criar um user on boarding para deixar a navegação pelo app mais iterativa

### Qual tipo de mudança o Pull Request introduz?
Adiciona um user on boarding à tela inicial do aplicativo

### Qual é o comportanto atual?
Não é exibida nenhuma informação adicional sobre o app para o usuário

### Qual é o novo comportamento?
Agora o usuário consegue ter uma visão inicial do app logo na primeira tela

### Quais as issues o Pull Request finaliza?
#374 

### _Uso do avaliador_
- [ ] Mensagens de commits seguem a guideline proposta;
- [ ] Os testes foram adicionados mantendo ou aumentando a cobertura de testes;
- [ ] Documentos necessários foram atualizados ou adicionados;

2018-06-18 12:25 UTC, luis-gustavo requested changes
Então galera, o aplicativo está com dois comportamentos errados:
1 - O UserOnboarding só deve aparecer na primeira vez que o usuário utiliza o app, e não toda vez que abrir o app.

2 - Por algum motivo a imagem do useronboarding está alterando demais imagens do aplicativo
![](https://i.imgur.com/17uqKSb.png)
![](https://i.imgur.com/CxxrwNy.png)
![](https://i.imgur.com/S1coitN.png)

2018-06-19 11:23 UTC, luis-gustavo commented
@gabrielalbino @helenagoulart Realmente, se desinstalar o app e instalar de novo as imagens não ficam zuadas. Entretanto ainda tem que arrumar a parada de só aparecer o onboarding na primeira vez que usar o app.

2018-06-19 13:47 UTC, miguelpimentel commented
O @luis-gustavo já deixou essas considerações.  Quando terminarem me marca que eu avalio.

2018-06-19 14:14 UTC, gabrielalbino commented
@miguelpimentel @luis-gustavo @guibaldissera fixed! ;)

2018-06-19 16:59 UTC, luis-gustavo approved these changes
Agora ta show! Bom trabalho, galera!

2018-06-19 23:21 UTC, miguelpimentel commented on project/app/src/main/java/com/nexte/nexte/UserOnBoardingView.kt
> +            if(board == 2) {
number magic, Hehehe

2018-06-19 23:22 UTC, miguelpimentel commented on project/app/src/main/java/com/nexte/nexte/UserOnBoardingView.kt
> +        if (userOnBoardingViewPager.currentItem == 0) {
Outro Heheh

2018-06-19 23:32 UTC, miguelpimentel approved these changes
Muito bom aos envolvidos, curti muito!

2018-06-19 23:33 UTC, merged