Feature/378
fga-eps-mds/2018.1_Nexte pull request #430
Opened 2018-06-18 16:17 UTC by mbslet

## Descrição
Esse Pull Request introduz a funcionalidade de  a partir do contato do jogador, fazer ligações, adicionar o contato, abir a opção de whatsapp e telegram.

### Qual tipo de mudança o Pull Request introduz?
Traz ação ao botão de contato para que faça interações entre os jogadores.

### Qual é o comportanto atual?
O botão de contato não tem funcionalidade

### Qual é o novo comportamento?
O botão de contado da Show Profile agora tem ação e traz um alert dialog
### Quais as issues o Pull Request finaliza?
#378 
### _Uso do avaliador_
- [ ] Mensagens de commits seguem a guideline proposta;
- [ ] Os testes foram adicionados mantendo ou aumentando a cobertura de testes;
- [ ] Documentos necessários foram atualizados ou adicionados;

2018-06-18 16:47 UTC, miguelpimentel commented on project/app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.CALL_PHONE" />
Bom!

2018-06-18 16:48 UTC, miguelpimentel commented on project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileFragment.kt
> +    var buttonC: Button? = null
Que nome, hein.

2018-06-18 16:52 UTC, miguelpimentel reviewed
Muito bom. Entretanto, tem algumas coisitas Hehe. Seria legal mudar o nome do button C? Não?! Todas as formas de comunicação estão funcionando. Entretanto, se você não tiver o App ou Telegram o aplicativo crasha. Acredito que seja apenas uma validação que esteja faltando. Mas, parabéns aos envolvidos.

2018-06-18 16:52 UTC, luis-gustavo commented on project/app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.CALL_PHONE" />
kkkkkkkkkkkkkkkkk

2018-06-18 16:53 UTC, miguelpimentel requested changes
Validem se o user tem wpp e Telegram

2018-06-18 17:52 UTC, mbslet commented on project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileFragment.kt
> +    var buttonC: Button? = null
É verdade...

2018-06-18 19:23 UTC, mbslet commented
Pronto. Não achei uma mensagem de exceção caso não tenha o telegram, tentei aplicar o mesmo caso do whatsapp mas não funcionou, e só achei exceptions da api do telegram, entretanto posso tirar a opçao do telegram. A qualquer hora essa opção pode ser tirada mas cabe uma conversa para decidir.

2018-06-19 11:29 UTC, luis-gustavo approved these changes
Ficou show, parabéns galera!

2018-06-19 13:37 UTC, miguelpimentel approved these changes
Boa, agora sim @mbslet  e @guibaldissera! Muito bom!

2018-06-19 13:37 UTC, merged