Feature/375
fga-eps-mds/2018.1_Nexte pull request #447
Opened 2018-06-21 04:44 UTC by Geovannioj

## Descrição
Inclui a modificação do design da tela de Tenistas a serem desafiados, assim como adiciona novos dados a serem visualizados, de acordo com o protótipo feito pela Designer do time

### Qual tipo de mudança o Pull Request introduz?
Tela de tenistas com design e novas informações pertinentes

### Qual é o comportanto atual?
Tela de tenistas sem design e faltando informações básicas

### Qual é o novo comportamento?
Tela de tenistas com design e novas informações pertinentes

### Quais as issues o Pull Request finaliza?
#375 

### _Uso do avaliador_
- [ ] Mensagens de commits seguem a guideline proposta;
- [ ] Os testes foram adicionados mantendo ou aumentando a cobertura de testes;
- [ ] Documentos necessários foram atualizados ou adicionados;

2018-06-21 12:36 UTC, luis-gustavo commented
@Geovannioj Pipeline quebrando e falta da um pull da dev

2018-06-21 13:53 UTC, Geovannioj commented
Beleza, Luis, estou resolvendo aqui, daqui a pouco subo um commit quando concertar.

2018-06-21 22:17 UTC, guibaldissera commented
Senhores, então, a tela está bem feiazinha, sem querer falar nada kkkkkkkk

2018-06-22 01:09 UTC, luis-gustavo commented
@guibaldissera isso é um request changes ?

2018-06-22 12:22 UTC, Geovannioj commented
O zeplin e como está agora não está tão diferente assim, inclusive no zeplin não tem o botão de mandar desafios, a questão da medalha @guibaldissera lembro que vc falou pra Lorrany que era pra deixar pra lá e não colocar.
Então o que é pra mudar ?
<img width="583" alt="captura de tela 2018-06-22 as 09 18 39" src="https://user-images.githubusercontent.com/13878770/41776289-90270266-75fd-11e8-9186-f61510a6d96a.png">

2018-06-23 06:26 UTC, miguelpimentel commented
Pipeline está quebrado

2018-06-23 10:36 UTC, miguelpimentel commented
É o teste de rankingPresenter, imagino que seja o date. Vou verificar mais tarde, qualquer coisa crio um hotfix mais tarde.

2018-06-23 17:52 UTC, luis-gustavo commented on project/app/src/main/java/com/nexte/nexte/PlayersListScene/PlayersListPresenter.kt
>              formattedPlayers += formattedPlayer
Na linha 73 tem que validar se existe profile picture. Com esse force cast da dando crash aqui.

2018-06-23 17:52 UTC, luis-gustavo requested changes
Arrumando o que disse, dá pra aceitar

2018-06-23 17:52 UTC, Geovannioj commented
Beleza, vou arrumar isso.

2018-06-23 20:05 UTC, luis-gustavo approved these changes

2018-06-23 22:14 UTC, miguelpimentel commented on project/app/src/main/java/com/nexte/nexte/PlayersListScene/PlayersListFragment.kt
> +        presenter.challengeManager = ChallengeManager()
Agora sim!

2018-06-23 22:14 UTC, miguelpimentel commented on project/app/src/main/java/com/nexte/nexte/PlayersListScene/PlayersListFragment.kt
> +        rankingFragment.setUserGameCircle(this?.circulo1, currentPlayer.userLastGames[0])
Esse circulo1, 2, 3, 4 e 5. KKKKKKK

2018-06-23 22:18 UTC, miguelpimentel commented on project/app/src/main/java/com/nexte/nexte/PlayersListScene/PlayersListModel.kt
> +                                  var rankingPosition: String,
Agora tem muitos detalhes!

2018-06-23 22:19 UTC, miguelpimentel approved these changes
Muito bom, @Geovannioj!

2018-06-23 22:19 UTC, merged