Feature/393
fga-eps-mds/2018.1_Nexte pull request #451
Opened 2018-06-21 19:14 UTC by miguelpimentel

## Descrição
Efetiva o login do usuário

### Qual tipo de mudança o Pull Request introduz?
Efetiva o login do usuário, ou seja, pega os dados da autenticação com o server, muda o status para usuário real, muda instancia de dados locais 

### Qual é o comportanto atual?
Apenas existe a opção de usuário moscado

### Qual é o novo comportamento?
Login efetivo com a aplicação

### Quais as issues o Pull Request finaliza?
#393 

### _Uso do avaliador_
- [ ] Mensagens de commits seguem a guideline proposta;
- [ ] Os testes foram adicionados mantendo ou aumentando a cobertura de testes;
- [ ] Documentos necessários foram atualizados ou adicionados;

2018-06-21 19:47 UTC, luis-gustavo requested changes
Vei, cobertura de testes ta caindo demais. De 88% ta caindo pra 83%, não rola de aceitar assim. Tem que, no mínimo, manter.

2018-06-21 19:51 UTC, miguelpimentel commented
Esse PR vai ficar aberto, porque tem outra história de Login, e nela que vou fazer os testes. Porque na real, tive que mudar tudo. E no outro os testes vão ser quebrados e refeitos de novo. Então, não faz sentido eu arrumar esses testes se em outra feature vou ter que refazer isso.

2018-06-21 19:51 UTC, miguelpimentel commented
Vai mudar muito ainda essa scena.

2018-06-26 01:27 UTC, luis-gustavo commented
@miguelpimentel Ta dando conflito aqui agora

2018-06-27 13:06 UTC, miguelpimentel commented
@guibaldissera depois dá uma olhada aqui

2018-06-27 13:33 UTC, luis-gustavo commented
@miguelpimentel Pra você ta dando 15 erros ao rodar o aplicativo nessa branch também ?

2018-06-27 15:41 UTC, luis-gustavo submitted a review, later dismissed
Agora sim, manteve a cobertura

2018-06-28 04:28 UTC, guibaldissera submitted a review, later dismissed

2018-06-28 13:54 UTC, luis-gustavo approved these changes

2018-06-28 13:55 UTC, luis-gustavo commented
@mbslet O cliente recusou. Só lamento.

2018-06-28 13:55 UTC, closed without merging